metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.178.70, mac: '00:23:24:CE:35:F5', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal1: {ansible_host: 192.168.178.68, mac: '00:23:24:CA:A0:9B', disk: sda, network_interface: eno1}

